### ISSUE TITLE
Cloning this repo downloads about 200+ MByte - ?!

### ISSUE THREAD

**Issue by pmario** [TiddlyWiki/TiddlyWikiLinks#23]
Cloning this repo downloads about 210 MByte - IMO that shouldn't be the case for a little bit of links. 
I did expect it to be 1 or 2 MB ... 

Do you know, where this horrendous size comes from?

**Comment by Jermolene** [comment]
The size of the repo is because of the gh-pages branch, which contains the static output. It's one of the disadvantages of using GitHub Pages in that mode (rather than the separate, per-organisation pages repo).

**Comment by Jermolene** [comment]
I propose that we use a different repo for the gh-pages branch to resolve the OP.

**Comment by pmario** [comment]
I think that's only an issue at the very first sync. I didn't expect it. ... I'll close the issue.

**Comment by Jermolene** [comment]
Thanks @pmario the trouble is that it's going to get worse and worse the longer the site is running, so I do propose to fix this as part of some other work.

**Comment by pmario** [comment]
>Thanks @pmario the trouble is that it's going to get worse and worse the longer the site is running, so I do propose to fix this as part of some other work.

Ahhh. OK. Didn't know that. I did update the branch with VS-Code and it needed about a second or 2

**Comment by Jermolene** [comment]
We now use a separate repo for the GitHub pages output of TiddlyWikiLinks: https://github.com/TiddlyWiki/links.tiddlywiki.org-gh-pages
