### ISSUE TITLE
Uppercase topic link directs you to lowercase topic

### ISSUE THREAD

**Issue by Marxsal** [TiddlyWiki/TiddlyWikiLinks#25]
Go to topics. Currently you will see "Plugin (53)" and "plugin (25)". Click on the uppercase version. It will take you to the "plugin (25)" results. Effectively, 53 plugins are unavailable through the interface.

**Comment by Jermolene** [comment]
Thanks @Marxsal I can confirm the problem – the two topics "Plugin" and "plugin" are slugifying to the same URL. This will be fixed with the work I'm doing at the moment on topic aliases.

**Comment by Jermolene** [comment]
This was fixed by the switch to a TW5 UI.
