### ISSUE TITLE
Search only returns lower case results.

### ISSUE THREAD

**Issue by Marxsal** [TiddlyWiki/TiddlyWikiLinks#26]
Go to the search box. Type "plug". Or type "Plug". Either way you will only see 5 topics, and they are all lowercase. Click on "plugin" and it will take you to topic "plugin (25)", which represents only the lowercase topic name -- there are 53 other items under topic "Plugin".

**Comment by Jermolene** [comment]
Thanks @Marxsal I can confirm the issue – the JavaScript that is handling the search doesn't know how to slugify the topics correctly, and is linking to the unslugified version of the title.

**Comment by Jermolene** [comment]
This was fixed by the switch to a TW5 UI.
