### ISSUE TITLE
How to fast start? How to save?

### ISSUE THREAD

**Issue by Marxsal** [TiddlyWiki/TiddlyWikiLinks#29]
Questions --

Is there a way to fast-start the server without checking for new items every time?

The basic setup won't let you save new tiddlers. I tried adding the tiddlyweb and filesystem plugins, but that resulted in non-stop errors. Is there a way to add new tiddlers?

Thanks!

**Comment by Jermolene** [comment]
Thanks @Marxsal I've added a new option `npm run edit` that runs up the server for local editing. You'll need to have collected the links at least once in order to have some data to display.
