### ISSUE TITLE
It seems that github workflow will not run automatically

### ISSUE THREAD

**Issue by oeyoews** [TiddlyWiki/TiddlyWikiLinks#60]
<img width="432" alt="image" src="https://github.com/TiddlyWiki/TiddlyWikiLinks/assets/72405338/c9b82e3a-e7a6-4faa-920c-818af27a559a">

<img width="864" alt="image" src="https://github.com/TiddlyWiki/TiddlyWikiLinks/assets/72405338/80ab8d44-3e4e-4f65-a5ee-008cdb85b830">

**Comment by Jermolene** [comment]
Thanks @oeyoews I haven't come across that error before.

I see the same message, but with a button for re-enabling actions, which I have clicked. Fingers crossed things will work now.
